[package]
name = "tail-rust"
version = "0.1.0"
authors = ["saber.wu <saber.wu@trantect.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1.28"
inotify = "0.7.0"
